---
title: "Lab 03 - Nobel laureates"
author: "Lindley Slipetz"
date: "02/09/2021"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE, warning = FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1

```{r glimpse}
glimpse(nobel)
```
There are 935 rows and 26 columns. The rows represent nobel laureates.

### Exercise 2

```{r noble_living}
nobel_living <- nobel %>%
  filter(is.na(country) == FALSE,
         gender != "org",
         is.na(died_date))

```
### Exercise 3

```{r create_cu}
nobel_living <- nobel_living %>%
  mutate(
    country_us = if_else(country == "USA", "USA", 
                         "Other")
                )
```

```{r filter_field}
nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))
```

```{r bar_graph}
ggplot(nobel_living, aes(x=factor(country_us)))+
  geom_bar(stat="count", width=0.7, fill="black")+
  facet_wrap(~category, nrow = 2) +
  labs(x = "Country of Nobel", 
      title = "US vs other countries for Nobel laureates by category") +
  coord_flip()
```
The claim that most nobels come from the US is supported. It remains to be seen if, of those from the US, they come from other countries.

### Exercise 4

...

### Exercise 5

...

### Exercise 6

...
